name: Azure Pipelines
variables:
  python.version: '3.7.6'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
      # Needed for Terraform VM deployment
    - task: InstallSSHKey@0
      displayName: 'Install an SSH key'
      inputs:
        #knownHostsEntry: '$(Parameters.hostName)'
        knownHostsEntry: '|1|ArQFt+580lWYUA35cvpFMb6Wbyg=|gKva90Ey+5D3b9+JwlUWci9EHfs= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H |1|UuptiHysPkO0EKmuAaRqplmQzJc=|weO0Lm9ldtqMLPS+H/tJMpuzR2o= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8qYbXXpA9AqJ36AcO0lxaS70tz2F34/BlMVME/DbhgnRnq5b+9F8yc7Smno0M3X8uK3W7qRHAPmj/p+8ANCUvNn0KCKqPI2r0AsDqCovvDW5l4xl8k/1dsecR8JESNqIN17Q13sDV1q4u/NmIVzMPyTfpKPyfj60eioFgpazolov8fSQ8amrpYJStCzLjtzcxaqC7v7tDrr4/4Y4CqQVhhH4lGZolme9wi0xSeAqdr3gi1nbB0FHBgiJVT5Md8ZDDcVv8tIEYpSPdSMGocjqAcdEBxR0epYj2KZUxX87wLzfuUMdT7ImFRs/mz4RbHLECpczgGkJoXohe7Q60WBfD u2benoit@gmail.com '
        sshKeySecureFile: 'id_rsa'
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      displayName: 'Use Terraform latest'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    - task: TerraformTaskV1@0
      displayName: 'terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceArm: 'quality'
        backendAzureRmResourceGroupName: 'azuredevops'
        backendAzureRmStorageAccountName: 'tstate14906'
        backendAzureRmKey: 'terraform.tfstate'
        backendAzureRmContainerName: tstate
    - task: TerraformCLI@0
      displayName: 'terraform validate'
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    - task: TerraformCLI@0
      displayName: 'terraform apply'
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    - task: ArchiveFiles@2
      displayName: 'Archive Autmated Tests'
      inputs:
        rootFolderOrFile: 'automatedtesting'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-automatedtests.zip'
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: 'automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
    
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-automatedtests.zip
      displayName: 'Upload Automatedtests'
      artifact: drop-automatedtests

      # Running Postman
    - task: CmdLine@2
      displayName: 'Running Postman Test'
      inputs:
        script: |
          npm install -g newman
          newman run StarterAPIs.json -e StarterAPIEnvironment.postman_environment.json  --reporters cli,junit --reporter-junit-export junitReport.xml
          #newman run StarterAPIs.json --reporters cli,junit --reporter-junit-export junitReport.xml
        workingDirectory: $(System.DefaultWorkingDirectory)/automatedtesting/postman
    - task: Bash@3
      displayName: 'Searching for Report'
      inputs:
        targetType: 'inline'
        script: |
          #! /bin/bash
          pwd
          echo "$(System.DefaultWorkingDirectory)"
          locate junitReport.xml
          ls -lrthaR
          #cat $(System.DefaultWorkingDirectory)/automatedtesting/postman/junitReport.xml           
          cat $(System.DefaultWorkingDirectory)/automatedtesting/postman/junitReport.xml      
    - task: PublishTestResults@2
      displayName: 'Publish Postman Test Result'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'junitReport.xml'
        searchFolder: $(System.DefaultWorkingDirectory)/automatedtesting/postman/
        testRunTitle: 'Postman Results'
    - task: CopyFilesOverSSH@0
      displayName: 'Copy files to VM'
      inputs:
        sshEndpoint: sshquality
        contents: '*/*/*py*'
        readyTimeout: '20000'
        overwrite: true
        flattenFolders: false
        sourceFolder: ''

# Deployment Stage
- stage:
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'DeploymentEnv'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'quality'
              appName: 'quality-app'
              appType: webAppLinux
              deploymentMethod: zipDeploy
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip

  - deployment: VMDeploy
    displayName: Configure VM
    environment:
      name:  ProductionEnv
      resourceType: VirtualMachine
      tags: myVM
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
               
                sudo apt-get upgrade -y
                sudo apt-get install python3-pip -y
                sudo apt-get install unzip -y
                sudo apt-get install -y chromium-browser
                pip3 install selenium
                export PATH=$PATH:some/path
                echo "Output of PATH"
                echo $PATH
                echo "Hello World this works"
                sudo rm -rf chromedriver*
                wget "https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip"
          
          - task: ExtractFiles@1
            displayName: 'Extract files'
            inputs:
              archiveFilePatterns:  '*chromedriver_linux64.zip'
              destinationFolder: ''
              cleanDestinationFolder: false
              
          - task: Bash@3
            displayName: 'Complete Setup of Chromedriver in VM'
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
    
                pwd
                sudo cp chromedriver /usr/bin
                echo "Done Settingup"  

        #Running Selenium Test
          - task: Bash@3
            displayName: 'Running Selenium Test'
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
                pwd
                echo "Hello World this works"
                cd /home/benoit/automatedtesting/selenium/
                #wget https://chromedriver.storage.googleapis.com/81.0.4044.138/chromedriver_linux64.zip
                #unzip chromedriver_linux64.zip
                #cat /home/casita/automatedtesting/selenium/login.py
                python3 /home/benoit/automatedtesting/selenium/login.py
 
  # Running Jmeter Tests
  - job: Jmeter
    pool:
      vmImage: 'ubuntu-latest'
    steps:
#    - task: JavaToolInstaller@0
#      displayName: 'Install Java 8'
#      inputs:
#        versionSpec: '8'
#        jdkArchitectureOption: 'x64'
#        jdkSourceOption: 'PreInstalled'
    - task: AlexandreGattiker.jmeter-tasks.custom-jmeter-installer-task.JMeterInstaller@0
      displayName: 'Install JMeter 5.2.1'
    - task: Bash@3
      displayName: 'Run Jmeter test'
      inputs:
        targetType: 'inline'
        script: |
          locate jmeter
          jmeter -n -t automatedtesting/jmeter/activities.jmx -Jresdir=automatedtesting/jmeter/pages.csv